efRuntime
RedisLabsModules/VectorSimilarity pull request #26
Opened 2021-07-26 20:48 UTC by DvirDukhan

2021-07-29 06:11 UTC, ashtul reviewed
Looks good with a minor question -
In our discussion, I understood we want to set efRuntime at query time. Here we set it at init time.
Do we plan to add query time param later?

2021-08-01 07:45 UTC, ashtul requested changes
@DvirDukhan  Please make the clang-format / deletion PR in a separate PR.
There are meaningful changes here and it gets lost in all the formatting changes.

2021-08-01 10:28 UTC, DvirDukhan commented
@ashtul done

2021-08-01 13:33 UTC, ashtul approved these changes
LGTM with one minor comment :+1:

2021-08-01 13:33 UTC, ashtul commented on src/VecSim/vecsim.h
> +} VecSimIndexInfo;
new line

2021-08-01 14:57 UTC, merged